### ISSUE TITLE
Use packaged grocy-docker release during Travis Builds

### ISSUE THREAD

**Issue by jayaddison** [BlueBlueBlob/pygrocydm#4]
Currently `pygrocydm`'s Travis CI pre-install process retrieves the latest `master` version of [grocy-docker's `Dockerfile-grocy`](https://github.com/grocy/grocy-docker/).

https://github.com/BlueBlueBlob/pygrocydm/blob/44c3578c5bd710f48ab6cb301e91b44534a0fe32/.travis.yml#L14

This could be unreliable since it may build against unreleased and untested versions of `grocy-docker`.

If possible it'd be safest to use `docker pull`, and perhaps even to pick a specific tag from Docker Hub once you've found an image that's reliable and safe enough for development purposes.

**Comment by BlueBlueBlob** [comment]
Thx. I'm just waiting the latest version on docker hub. 
Curl was find to grab latest Grocy version. But need a build at every time. I guess I have to look into commit history to download latest image working.

**Comment by BlueBlueBlob** [comment]
Fixed with 3f2ab310812be99072bc47079b3c5e0e9af06226

Thx a lot for your work 👍
